### ISSUE TITLE
docker-compose.yml 파일 만들기

### ISSUE THREAD

**Issue by nonalias** [42Sloth/game-service#10]
dockerizing하여 인프라 구축 후 개발을 합니다.

### 예제
* docker-compose.yml
```
version: '3.8'
services:
  database:
    image: postgres:13.3
    volumes:
      - '/var/lib/postgresql/data'
    env_file:
      - ./postgres.env
    restart: unless-stopped
    ports:
      - '5432:5432'
```

### BE, FE, Database dockerizing 작업
